// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum PipApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct PipStatus: Hashable, CustomStringConvertible {
  var isSupported: Bool
  var isActive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipStatus? {
    let isSupported = pigeonVar_list[0] as! Bool
    let isActive = pigeonVar_list[1] as! Bool

    return PipStatus(
      isSupported: isSupported,
      isActive: isActive
    )
  }
  func toList() -> [Any?] {
    return [
      isSupported,
      isActive,
    ]
  }
  static func == (lhs: PipStatus, rhs: PipStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PipApiPigeonInternal.deepEquals(lhs.isSupported, rhs.isSupported) && PipApiPigeonInternal.deepEquals(lhs.isActive, rhs.isActive)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PipStatus")
    PipApiPigeonInternal.deepHash(value: isSupported, hasher: &hasher)
    PipApiPigeonInternal.deepHash(value: isActive, hasher: &hasher)
  }

  public var description: String {
    return "PipStatus(isSupported: \(String(describing: isSupported)), isActive: \(String(describing: isActive)))"
  }
}

private class PipApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PipStatus.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PipApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PipStatus {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PipApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PipApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PipApiPigeonCodecWriter(data: data)
  }
}

class PipApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PipApiPigeonCodec(readerWriter: PipApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EasyPipApi {
  func isPiPSupported() throws -> Bool
  func enterPiP(width: Int64, height: Int64) throws
  func getPiPStatus() throws -> PipStatus
  func setupAutoPiP(width: Int64, height: Int64) throws
  func updatePlaybackState(isPlaying: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EasyPipApiSetup {
  static var codec: FlutterStandardMessageCodec { PipApiPigeonCodec.shared }
  /// Sets up an instance of `EasyPipApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EasyPipApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isPiPSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_pip_plugin.EasyPipApi.isPiPSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPiPSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isPiPSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPiPSupportedChannel.setMessageHandler(nil)
    }
    let enterPiPChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_pip_plugin.EasyPipApi.enterPiP\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enterPiPChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          try api.enterPiP(width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enterPiPChannel.setMessageHandler(nil)
    }
    let getPiPStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_pip_plugin.EasyPipApi.getPiPStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPiPStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPiPStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPiPStatusChannel.setMessageHandler(nil)
    }
    let setupAutoPiPChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_pip_plugin.EasyPipApi.setupAutoPiP\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupAutoPiPChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          try api.setupAutoPiP(width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setupAutoPiPChannel.setMessageHandler(nil)
    }
    let updatePlaybackStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_pip_plugin.EasyPipApi.updatePlaybackState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePlaybackStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isPlayingArg = args[0] as! Bool
        do {
          try api.updatePlaybackState(isPlaying: isPlayingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePlaybackStateChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol EasyPipFlutterApiProtocol {
  func onPiPStatusChanged(isActive isActiveArg: Bool) async throws
  func onPlayPauseActionTriggered() async throws
}
class EasyPipFlutterApi: EasyPipFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PipApiPigeonCodec {
    return PipApiPigeonCodec.shared
  }
  func onPiPStatusChanged(isActive isActiveArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.easy_pip_plugin.EasyPipFlutterApi.onPiPStatusChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([isActiveArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onPlayPauseActionTriggered() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.easy_pip_plugin.EasyPipFlutterApi.onPlayPauseActionTriggered\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
